package com.fazziclay.opentoday.app.items.tick;

public enum TickTarget {
    ITEM_NOTIFICATIONS,
    ITEM_NOTIFICATION_SCHEDULE,
    ITEM_NOTIFICATION_UPDATE,
    ITEM_CALLBACKS,
    ITEM_DAY_REPEATABLE_CHECKBOX_UPDATE,
    ITEM_DEBUG_TICK_COUNTER_UPDATE,
    ITEM_FILTER_GROUP_TICK,
    ITEM_MATH_GAME_UPDATE
}
